import { TypographyStylesProvider } from '@mantine/core';

export default function Privacy() {
  return (
    <TypographyStylesProvider>
      <div
        dangerouslySetInnerHTML={{
          __html: `
          <div>
          <h2>Privacy Policy</h2>
          <p>Last updated: August 01, 2021</p>
          <p>
            This privacy policy describes our policies and procedures for
            Collection, use, and disclosure of your information when you use the Service
            use, and informs you of your privacy rights and how the law
            She protects.
          </p>
          <p>
            We use your personal information to provide and improve
            of service. By using the service, you agree to the
            Collection and use of information in accordance with this privacy policy
            agreed. This privacy policy was created using the
            Privacy policy generator created.
          </p>
          <h3>Construction and definitions</h3>
          <h4>Design</h4>
          <p>
            The words whose first letters are capitalized have the under
            meanings defined in the following conditions. The following
            Definitions have the same meaning whether or not they are in the singular
            or in the plural.
          </p>
          <h4>Definitions</h4>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li>
              <p>
                Account means a unique account created for you to
                access our Service or parts of our Service.
              </p>
            </li>
            <li>
              <p>
                Company (referred to in this Agreement as either "the Company",
                "we", "us" or "our" refers to HERACL Roman
                Khymych, ul. Krynicka 3 80-393 Gdansk in Poland.
              </p>
            </li>
            <li>
              <p>
                Cookies are small files placed on your computer by a website,
                Your mobile device or another device and the under
                contain other information about your surfing behavior on this website.
              </p>
            </li>
            <li>
              <p>The country refers to: Poland</p>
            </li>
            <li>
              <p>
                Device means any device that can access the Service, e.g. B. a
                computer, a mobile phone or a digital tablet.
              </p>
            </li>
            <li>
              <p>
                Personal data is any information relating to a
                identified or identifiable person.
              </p>
            </li>
            <li>
              <p>Service refers to the website.</p>
            </li>
            <li>
              <p>
                Service provider is any natural or legal person who
                Data processed on behalf of the company. This refers to
                Third party companies or individuals employed by the Company
                are, in order to facilitate the service, the service on behalf of the company
                provide services related to the Service
                provide or the company in analyzing the use of the service
                to support.
              </p>
            </li>
            <li>
              <p>
                Usage Data refers to automatically collected data that
                either through the use of the service or through the infrastructure of the
                generated by the service itself (e.g. the duration of a page visit).
              </p>
            </li>
            <li>
              <p>
                Website refers to Heracl, accessible from https://www.heracl.com
              </p>
            </li>
            <li>
              <p>
                It means the person accessing or using the Service,
                or the company or other legal entity on whose behalf
                such person accesses or uses the Service, as the case may be.
              </p>
            </li>
          </ul>
          <h3>Collection and use of your personal information</h3>
          <h4>Types of Data Collected</h4>
          <h4>Personal Information</h4>
          <p>
            While using our service, we may ask you to
            communicate certain personal data that will be used for this purpose
            able to contact or identify you. Personal
            identifiable information may include:
          </p>
          <ul>
            <li><p>Email address</p></li>
            <li><p>Usage data</p></li>
          </ul>
          <h4>Usage Data</h4>
          <p>Usage data is automatically collected when using the service.</p>
          <p>
            Usage data may include information such as the internet protocol address
            Your device (e.g. IP address), browser type, browser version used by
            pages of our service you visited, the time and date of your
            visit, time spent on these pages, unique device identifiers
            and other diagnostic data.
          </p>
          <p>
            If you are accessing the Service with or through a mobile device, you may
            we collect certain information automatically, including but not limited to
            limited to the type of mobile device you are using, the
            unique ID of your mobile device, the IP address of your mobile device, your
            mobile operating system, the type of mobile you are using
            Internet browsers, unique device identifiers and other diagnostic data.
          </p>
          <p>
          We may also collect information that your browser sends when you
     visit our Service or when you access the Service from a mobile device
     access.
   </p>
   <h4>Tracking Technologies and Cookies</h4>
   <p>
     We use cookies and similar tracking technologies to track activity
     track and store certain information on our Service. At
     The tracking technologies used are beacons, tags and
     Scripts for collecting and tracking information and for improvement
     and analysis of our service. About the technologies we use
     belong:
   </p>
   <ul>
     <li>
       <p>
         Cookies or browser cookies. A cookie is a small file that is stored on
         is saved to your device. You can tell your browser all
         Reject cookies or indicate when a cookie is being sent. If
         However, if you do not accept cookies, you may be able to use some
         Do not use parts of our service. Unless you use your browser like that
         If you have set it to reject cookies, our service can accept cookies
         use.
       </p>
     </li>
     <li>
       <p>
         Flash cookies. Certain features of our Service may be local
         Stored objects (or Flash cookies) use to store information
         about your preferences or your activities on our Service
         collect and store. Flash cookies will not have the same
         Browser settings managed like the browser cookies. Further
         Information on how to delete Flash cookies can be found here
         under "Where can I find the settings to disable or delete
         Change locally stored objects?" below
         https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_.
       </p>
     </li>
     <li>
       <p>
         web beacons. Certain areas of our Service and our emails
         may contain small electronic files known as web beacons (aka
         known as clear gifs, pixel tags, and single-pixel gifs).
         are and which allow the company, for example, the users
         to count who have visited these pages or opened an e-mail,
         and other related website statistics (e.g.
         Recording the popularity of a specific area and reviewing it
         of system and server integrity).
       </p>
     </li>
   </ul>
   <p>
     Cookies can be "persistent" or "session" cookies. Persistent cookies
     remain on your computer or mobile device when you go offline,
     while session cookies are deleted as soon as you open your web browser
     close. You can learn more about cookies here: All about cookies
     from TermsFeed.
   </p>
   <p>
     We use both session cookies and persistent cookies for the
     purposes listed below:
   </p>
   <h4>Necessary / essential cookies</h4>
   <p>Type: session cookies</p>
   <p>Managed by: Us</p>
   <p>
     Purpose: These cookies are essential to provide you with access to the website
     provide available services and your use of some
     enable their functions. They help authenticate
     users and prevent fraudulent use of user accounts. Without
     these cookies cannot provide the services you have requested
     provided and we only use these cookies to provide you with this
     to provide services.
   </p>
   <h4>Cookies Policy / Notice Acceptance Cookies</h4>
   <p>Type: Persistent cookies</p>
   <p>Managed by: Us</p>
   <p>
     Purpose: These cookies identify whether users are using
     Have accepted cookies on the website.
   </p>
   <p>Functional cookies</p>
   <p>Type: Persistent cookies</p>
   <p>Managed by: Us</p>
   <p>
     Purpose: These cookies enable us to collect data from you when you use the
     store decisions made on the website, e.g. B. Your login details
     or your language preference. The purpose of these cookies is to provide you with a
     to provide a more personal experience and to avoid interfering with your
     Having to re-enter your preferences each time you use the website.
   </p>
   <p>
     Learn more about the cookies we use and yours
     For choices regarding cookies, see our
     Cookie Policy or in the Cookies section of our Privacy Policy.
   </p>
   <h3>Use of your personal information</h3>
   <ul>
     <li>
       <p>
         The company may collect personal information for the following purposes
         use:
       </p>
     </li>
     <li>
       <p>
         To provide and maintain our Service, including
         Monitoring the use of our service
         it.
       </p>
     </li>
     <li>
       <p>
         To manage your account: to register you as a user of the Service
         manage. The personal information you provide may
         Give you access to various features of the Service that are available to you
         available as a registered user.
       </p>
     </li>
     <li>
       <p>
         For the performance of the contract: to develop, comply with and implement the
         contract of sale for the products, items or
         Services or any other contract with us for the Service.
       </p>
     </li>
     <li>
       <p>
         To contact you: To contact you by email, phone calls, SMS or
         other equivalent forms of electronic communication
         contact, such as B. Push notifications from a mobile application
         regarding updates or informative notices in the
         related to the functions, products or contracted
         Services, including security updates when
         this is necessary or appropriate for their implementation.
       </p>
     </li>
     <li>
       <p>
         To provide you with news, special offers and general information about
         other goods, services and events we offer
         to send you that are similar to those that you have already purchased or
         have requested, unless you have opted out of receiving such
         information decided.
       </p>
     </li>
     <li>
       <p>
         To manage your requests: To process your requests to us and
         manage.
       </p>
     </li>
     <li>
       <p>
         For business transfers: We may use your information to make a
         merger, divestment, restructuring, reorganization, dissolution or
         another sale or transfer of some or all of ours
         to evaluate or carry out assets, whether as ongoing
         operating or as part of a bankruptcy, liquidation or a
         similar process where personal information we collect about our
         service users own belong to the transferred assets.
       </p>
     </li>
     <li>
       <p>
         For other purposes: We may use your data for other purposes,
         such as B. for data analysis, to determine usage trends, for
         Determining the effectiveness of our advertising campaigns and to evaluate and
         improving our service, products, services,
         our marketing and your experiences.
       </p>
     </li>
   </ul>
   <p>
     We may disclose your personal information in the following situations:
   </p>
   <ul>
     <li>
       <p>
         With service providers: We may share your personal information with
         Share with service providers to monitor usage of our service
         and analyze and to contact you.
       </p>
     </li>
     <li>
       <p>
         For business transfers: We may transfer your personal data in
         connection with or during negotiations for a merger, the
         Sale of company assets, financing or acquisition
         all or part of our business by another
         share or transfer business.
       </p>
     </li>
     <li>
       <p>
         With Affiliates: We may share your information with our affiliates
         pass on company; in this case we oblige them
         Affiliates to comply with this Privacy Policy. To
         the affiliated companies include our parent company and all
         other subsidiaries, joint venture partners or others
         Companies that we control or that are under common control
         stand with us.
       </p>
     </li>
     <li>
       <p>
         With business partners: We may share your information with our
         business partners to offer you certain products,
         to offer services or promotions.
       </p>
     </li>
     <li>
       <p>
         With other users: when you share personal information or
         otherwise in the public areas with other users
         interact, this information can be viewed by all users
         and disseminated to the outside world.
       </p>
     </li>
     <li>
       <p>
         With your consent: With your consent, we can use your
         disclose personal information for any other purpose.
       </p>
     </li>
   </ul>
   <h3>Retention of your personal data</h3>
   <p>
     The company will only keep your personal data for as long as
     it is necessary for the purposes set out in this Privacy Policy
     is. We will keep your personal data
     ren and use
     to the extent necessary to comply with our legal obligations
     to comply (e.g. if we need to keep your data to comply with applicable
     to comply with the law), resolve disputes and our legal
     enforce agreements and policies.
   </p>
   <p>
     The company also stores usage data for internal analysis purposes.
     Usage data is generally retained for a shorter period of time,
     unless this data is used to ensure security or the
     improve functionality of our service, or we are lawful
     obliged to keep this data for longer periods.
   </p>
   <h3>Disclosure of your personal information</h3>
   <p>
     Your information, including personal data, will be stored in the
     Processed at the Company's operational offices and all other locations
     where the parties involved in the processing are based. The
     means that this data is sent to computers outside of your state, your
     province, your country or other governmental jurisdiction in which
     different data protection laws than those applicable in your jurisdiction
     and can be saved there.
   </p>
   <p>
     By agreeing to this Privacy Policy and subsequent
     You agree to the transmission of this data with this transmission
     agreed.
   </p>
   <p>
     The Company will take all reasonable steps to
     ensure that your data is secure and in accordance with this
     Privacy Policy will be treated and there will be no transmission of your
     personal information to an organization or country held when
     adequate controls are not in place to protect the security of your information
     and other personal information.
   </p>
   <h3>Disclosure of your personal information</h3>
   <h4>Business Transactions</h4>
   <p>
     If the company participates in a merger, acquisition, or sale of
     assets involved may transfer your personal information
     become. We will inform you before your personal information is transferred
     will be subject to a different privacy policy.
   </p>
   <h4>Law Enforcement</h4>
   <p>
     In certain circumstances, the Company may be required to
     disclose personal information when required by law
     or in response to legitimate requests from public authorities (e.g. a court
     or a government agency).
   </p>
   <h4>Other legal requirements</h4>
   <p>
     The company may disclose your personal information if it is in good
     believes that such action is necessary to:
   </p>
   <ul>
     <li>
       <p>To comply with a legal obligation:</p>
     </li>
     <li>
       <p>
         to protect and protect the rights or property of the company
         defend
       </p>
     </li>
     <li>
       <p>
         Preventing or investigating possible wrongdoing in
         connection with the service
       </p>
     </li>
     <li>
       <p>
         the personal safety of the users of the service or the
         protect public
       </p>
     </li>
     <li>
       <p>Protection against legal liability</p>
     </li>
   </ul>
   <h4>Security of your personal information</h4>
   <p>
     The security of your personal information is important to us, but think about it
     mind that no method of transmission over the Internet or the
     electronic storage is 100% secure. We try to keep your
     protect personal data by commercially reasonable means,
     however, cannot guarantee absolute security.
   </p>
   <h3>
     Detailed information about the processing of your personal data
   </h3>
   <p>
     The service providers we engage may have access to
     Your personal information. These third parties collect, store, use,
     process and transmit information about your activities on our
     Service in accordance with their privacy policy.
   </p>
   <p>Usage, performance and other</p>
   <p>We may use third parties to improve our service.</p>
   <ul>
     <li>
       <p>
         Squarespace: Their privacy policies can be found at
         https://www.squarespace.com/privacy.
       </p>
     </li>
   </ul>
   <h3>Privacy for children</h3>
   <p>
     Our service is not directed to persons under the age of 13. We collect
     does not knowingly collect personally identifiable information from anyone under the age of 13. If
     You are a parent or legal guardian and you know that your
     child has provided us with personal information, contact
     us please If we discover that we have personal data from
     Individuals under the age of 13 without verification of parental consent
     recorded
     we take steps to remove this data from our servers
     removed.
   </p>
   <p>
     When we rely on consent as the legal basis for processing
     of your data and your country require parental consent
     requires, we may require your parent's consent before we
     collect and use this data.
   </p>
   <h3>Links to other websites</h3>
   <p>
     Our Service may contain links to other websites that are not owned by us
     operate. If you click on a third party link,
     you will be redirected to the page of this third party. We recommend
     Urge you to review the privacy policies of any website you visit
     to read.
   </p>
   <p>
     We have no control over and accept no responsibility for the
     Content, the privacy policies or practices of any site or service
     third party
   </p>
   <h3>Changes to this Privacy Policy</h3>
   <p>
     We may update our privacy policy from time to time. We
     will notify you of any changes by posting the new one
     Post privacy policy on this page.
   </p>
   <p>
     We will inform you by e-mail and/or by means of a prominent notice
     our service before the change takes effect and update that
     Date of Last Update" at the top of this Privacy Policy.
   </p>
   <p>
     We encourage you to periodically review this Privacy Policy for changes
     to check. Changes to this Privacy Policy are effective when
     when they are published on this site.
   </p>
   <h3>Contact us</h3>
   <p>
     If you have any questions about this privacy policy, you can contact us
     to contact:
   </p>
   <ul>
     <li>
       <p>https://www.heracl.com/contact</p>
     </li>
   </ul>
</div>


          `,
        }}
      />
    </TypographyStylesProvider>
  );
}
